[package]
name = "hutspot"
version = "0.0.1"
edition = "2024"
authors = ["Snoep <maxim@snoep.io>"]

[dependencies]
glam = "0.29.3"
nalgebra = "0.33.2"

itertools = "0.14.0"
approx = "0.5.1"

pathfinding = "4.14.0"
ordered-float = "5.0.0"

log = "0.4.27"