[package]
name = "potpoursi"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
glam = "0.24.2"
log = "0.4.20"
bevy_render = "0.12.1"